#ifndef __layAmbFrame__
#define __layAmbFrame__

/**
@file
Subclass of AmbFrame, which is generated by wxFormBuilder.
*/

#include "moore_lay.h"
#include "paramb.h"

//// end generated include

/** Implementing AmbFrame */
class MooreLayAmbFrame : public AmbFrame
{
	public:
		/** Constructor */
		MooreLayAmbFrame( wxWindow* parent );
	//// end generated class members
		void setAmb(Paramb* a);
		void UpdateAmb();

	private:
		Paramb* amb;
};

#endif // __layAmbFrame__
