#ifndef __AxisFrame__
#define __AxisFrame__

/**
@file
Subclass of AxisFrame, which is generated by wxFormBuilder.
*/
#include "Moore.h"
#include "moore_lay.h"

//// end generated include

/** Implementing AxisFrame */
class MooreAxisFrame : public AxisFrame
{
	protected:
		// Handlers for AxisFrame events.
		void OnAxisSetting_changed( wxScrollEvent& event );
		void OnAxisSetting_changed( wxCommandEvent& event );

		void OnAxisSetting_changed();
	public:
		/** Constructor */
		MooreAxisFrame( wxWindow* parent );
	//// end generated class members

		void setMoore(Moore* m);

	private:
		Moore* moore;

};

#endif // __AxisFrame__
