#ifndef __CHRMeasFrame__
#define __CHRMeasFrame__

/**
@file
Subclass of CHRMeasFrame, which is generated by wxFormBuilder.
*/

#include "Moore.h"
#include "moore_lay.h"

//// end generated include

/** Implementing CHRMeasFrame */
class MooreCHRMeasFrame : public CHRMeasFrame
{
	protected:
		// Handlers for CHRMeasFrame events.
		void OnSpeed_Text( wxCommandEvent& event );
		void OnStartCHR_butClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MooreCHRMeasFrame( wxWindow* parent );
	//// end generated class members
		void setMoore(Moore* m);

	private:
		Moore* moore;

};

#endif // __CHRMeasFrame__
