#ifndef __layAmbFrame__
#define __layAmbFrame__

/**
@file
Subclass of AmbFrame, which is generated by wxFormBuilder.
*/

#include "moore_lay.h"
#include "paramb.h"

//// end generated include

/** Implementing AmbFrame */
class Moore_layAmbFrame : public AmbFrame
{
	protected:
		// Handlers for AmbFrame events.
		void OnTval_butClick( wxCommandEvent& event );
	public:
		/** Constructor */
		Moore_layAmbFrame( wxWindow* parent );
	//// end generated class members
		void setAmb(Paramb* a);
		void UpdateAmb();

	private:
		Paramb* amb;
};

#endif // __layAmbFrame__
