#ifndef __PosFrame__
#define __PosFrame__

/**
@file
Subclass of PosFrame, which is generated by wxFormBuilder.
*/

#include "moore_lay.h"
#include "Moore.h"

/** Implementing PosFrame */
class MoorePosFrame : public PosFrame
{
	protected:
		// Handlers for PosFrame events.
		void OnSetAbs_butClick(wxCommandEvent& event);
		void OnSetRel_butClick(wxCommandEvent& event);
		void OnSetZero_butClick(wxCommandEvent& event);
		void OnGotoZero_butClick(wxCommandEvent& event);
		void OnPosSettings_clicked(wxCommandEvent& event);
	public:
		/** Constructor */
		MoorePosFrame(wxWindow* parent);
		//// end generated class members

		void setMoore(Moore* m);
		void UpdatePosition();

	private:
		Moore* moore;
};

#endif // __PosFrame__
